// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJJ6O0fn6JKGn4YKtk8Erjff7XkdhJxt4',
    appId: '1:179015862283:web:94af86fe5e00e93d5d1f0e',
    messagingSenderId: '179015862283',
    projectId: 'demoapp2-3399d',
    authDomain: 'demoapp2-3399d.firebaseapp.com',
    storageBucket: 'demoapp2-3399d.firebasestorage.app',
    measurementId: 'G-TTJFHE6LLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA600TyADd2YjWdOVZwHcp6hNrz38FPQDA',
    appId: '1:179015862283:android:5c22111c6f958c355d1f0e',
    messagingSenderId: '179015862283',
    projectId: 'demoapp2-3399d',
    storageBucket: 'demoapp2-3399d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQpcJ_pictcbFhbZjlSIAXAnDvV2BBJA0',
    appId: '1:179015862283:ios:7487bf28016b74525d1f0e',
    messagingSenderId: '179015862283',
    projectId: 'demoapp2-3399d',
    storageBucket: 'demoapp2-3399d.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
